# # This Dockerfile is used to build the image available on DockerHub
# FROM centos:centos7 as build
FROM centos:centos7
ADD ./bin/multus-controller /
ADD ./images/start_controller.sh /
WORKDIR /

ENTRYPOINT ["/start_controller.sh"]
