# # This Dockerfile is used to build the image available on DockerHub
# FROM centos:centos7 as build
FROM centos:centos7
ADD ./images/cni /usr/src/multus-cni/cni
ADD ./images/package /usr/src/multus-cni/package
ADD ./bin /usr/src/multus-cni/bin
WORKDIR /

ADD ./images/entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
