apiVersion: v1
name: etcdhc
home: https://github.com/coreos/etcdcni
version: 0.8.1
appVersion: 3.4.1
description:
  Distributed reliable key-value store for the most critical data of a
  distributed system.
  Add extend configuration for HUAWEI Cloud
icon: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-horizontal-color.png
sources:
  - https://github.com/coreos/etcdcni
maintainers:
  - name: lachie83
    email: lachlan@deis.com
  - name: chris
    email: chris_waity@126.com
