apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: examplefix
  labels:
    app: examplefix
spec:
  serviceName: "examplefix"
  replicas: 2
  selector:
    matchLabels:
      app: examplefix
  template:
    metadata:
      labels:
        app: examplefix
      annotations:
        k8s.v1.cni.cncf.io/mynetworks: vxlan1
        k8s.v1.cni.cncf.io/extEnv: "Fix=vxlan1;Num=vxlan1:1"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - examplefix
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: examplefix
          image: busybox
          command:
            - sleep
            - "1000000"
          volumeMounts:
            - mountPath: /var/multus
              name: multus
      volumes:
        - hostPath:
            path: /root/multus
          name: multus
