apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-macvlanfix
  labels:
    app: example-macvlanfix
spec:
  serviceName: "macfix"
  replicas: 2
  selector:
    matchLabels:
      app: example-macvlanfix
  template:
    metadata:
      labels:
        app: example-macvlanfix
      annotations:
        k8s.v1.cni.cncf.io/mynetworks: macvlan3
        k8s.v1.cni.cncf.io/extEnv: "Fix=macvlan3"
    spec:
      containers:
        - name: example-macvlanfix
          image: busybox
          command:
            - sleep
            - "1000000"
          volumeMounts:
            - mountPath: /var/multus
              name: multus
      volumes:
        - hostPath:
            path: /root/multus
          name: multus
