apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkDefinition
metadata:
  name: macvlan2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth2",
      "mode": "bridge",
      "ipam": {
        "type": "host-etcd",
        "ranges": [
          [
            { 
              "subnet": "192.168.200.0/24",
              "lease_unit": "32"
            }
          ]
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.200.1"
      }
    }'
