# Default values for multus-etcd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

crd:
  kind: NetworkDefinition
  plural: network-definitions
  singular: network-definition
  short: netdef

daemonset:
  name: multus-hc
  namespace: kube-system
  image: "192.168.56.201:5000/multus-hc:v1.0.8"
  pullPolicy: "IfNotPresent"

etcdcni:
  name: etcdcni
  clientPort: 2379
  namespace: default
  image: 
    repository: "k8s.gcr.io/etcd-amd64"
    tag: "3.2.26"
    pullPolicy: "IfNotPresent"
  replicas: 3
  auth:
    client:
      ## Switch to encrypt client communication using TLS certificates
      secureTransport: false
      ## Switch to enable host authentication using TLS certificates. Requires existing secret.
      enableAuthentication: false
      ## Name of the existing secret containing cert files for peer communication.
      secretDirectory: "/etc/cni/net.d/multus.d/etcd/"
    peer:
      ## Switch to encrypt peer communication using TLS certificates
      secureTransport: false
      ## Switch to automatically create the TLS certificates
      useAutoTLS: false
      ## Switch to enable host authentication using TLS certificates. Requires existing secret.
      enableAuthentication: false
  persistentVolume:
    enabled: false
