# Default values for multus-etcd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

crd:
  kind: NetworkDefinition
  plural: network-definitions
  singular: network-definition
  short: netdef

daemonset:
  name: multus-ext
  namespace: kube-system
  image: "192.168.56.201:5000/multus-ext:v0.3.9"
  pullPolicy: "IfNotPresent"
  pullSecret: false
  registrySecret: registry-secret

controller:
  name: multus-controller
  namespace: kube-system
  image: "192.168.56.201:5000/multus-controller:v0.3.9"
  pullPolicy: "IfNotPresent"
  pullSecret: false
  registrySecret: registry-secret

etcdcni:
  # name: etcdcni
  # endpoints: "192.168.56.201:12379"
  endpoints:
    - '"192.168.56.201:12379"'
    # - '"192.168.56.202:12379"'
    # - "192.168.56.201:12379"
  clientPort: 2379
  namespace: default
  image:
    repository: "k8s.gcr.io/etcd-amd64"
    tag: "3.2.26"
    pullPolicy: "IfNotPresent"
  replicas: 3
  auth:
    client:
      ## Switch to encrypt client communication using TLS certificates
      secureTransport: false
      ## Switch to enable host authentication using TLS certificates. Requires existing secret.
      enableAuthentication: false
      ## Name of the existing secret containing cert files for peer communication.
      secretDirectory: "/etc/cni/net.d/multus.d/etcd/pki"
    peer:
      ## Switch to encrypt peer communication using TLS certificates
      secureTransport: false
      ## Switch to automatically create the TLS certificates
      useAutoTLS: false
      ## Switch to enable host authentication using TLS certificates. Requires existing secret.
      enableAuthentication: false
  persistentVolume:
    enabled: false
