apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-vxlan
  labels:
    app: example-vxvlan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-vxvlan
  template:
    metadata:
      labels:
        app: example-vxvlan
      annotations:
        k8s.v1.cni.cncf.io/mynetworks: vxlan1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
                - example-vxvlan
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: example-vxvlan
        image: busybox
        command:
        - sleep
        - "1000000"
        volumeMounts:
        - mountPath: /var/multus
          name: multus
      volumes:
      - hostPath:
          path: /root/multus
        name: multus


