apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkDefinition
metadata:
  name: vxlan1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "multus-vxlan",
    "master": "eth0",
    "ipMasq": true,
    "isGateway": true,
    "isDefaultGateway": false,
    "forceAddress": true,
    "hairpinMode": true,
    "vlan": 0,
    "vxlan":{
    "vxlanId": 201,
    "port": 8472,
    "learning": true,
    "gbp": false
    },
    "ipam": {
    "type": "multus-ipam",
    "ranges": [
    [
    {
    "subnet": "192.168.109.0/24",
    "rangeStart": "192.168.109.0",
    "rangeEnd": "192.168.109.223",
    "reserves":
    [
    "192.168.109.0",
    "192.168.109.255"
    ]
    }
    ]
    ],
    	"fixRange": {
			"subnet": "192.168.109.0/24",
			"rangeStart": "192.168.109.224",
			"rangeEnd": "192.168.109.255",
			"reserves": [
    "192.168.109.0",
    "192.168.109.255"
			]
		},
    "allocGW": true,
    "routes": [
    { "dst": "0.0.0.0/0" }
    ]
    }
    }'
